//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.16 at 07:11:58 PM CDT 
//


package com.canfer.app.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EstatusCuenta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EstatusCuenta"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Estado" type="{http://tempuri.org/}Status"/&gt;
 *         &lt;element name="Produccion" type="{http://tempuri.org/}Produccion"/&gt;
 *         &lt;element name="Pruebas" type="{http://tempuri.org/}Pruebas"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EstatusCuenta", propOrder = {
    "estado",
    "produccion",
    "pruebas"
})
public class EstatusCuenta {

    @XmlElement(name = "Estado", required = true)
    @XmlSchemaType(name = "string")
    protected Status estado;
    @XmlElement(name = "Produccion", required = true)
    protected Produccion produccion;
    @XmlElement(name = "Pruebas", required = true)
    protected Pruebas pruebas;

    /**
     * Gets the value of the estado property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getEstado() {
        return estado;
    }

    /**
     * Sets the value of the estado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setEstado(Status value) {
        this.estado = value;
    }

    /**
     * Gets the value of the produccion property.
     * 
     * @return
     *     possible object is
     *     {@link Produccion }
     *     
     */
    public Produccion getProduccion() {
        return produccion;
    }

    /**
     * Sets the value of the produccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Produccion }
     *     
     */
    public void setProduccion(Produccion value) {
        this.produccion = value;
    }

    /**
     * Gets the value of the pruebas property.
     * 
     * @return
     *     possible object is
     *     {@link Pruebas }
     *     
     */
    public Pruebas getPruebas() {
        return pruebas;
    }

    /**
     * Sets the value of the pruebas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pruebas }
     *     
     */
    public void setPruebas(Pruebas value) {
        this.pruebas = value;
    }

}
