//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.16 at 07:11:58 PM CDT 
//


package com.canfer.app.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.canfer.app.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.canfer.app.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValidaXML }
     * 
     */
    public ValidaXML createValidaXML() {
        return new ValidaXML();
    }

    /**
     * Create an instance of {@link ValidaXMLResponse }
     * 
     */
    public ValidaXMLResponse createValidaXMLResponse() {
        return new ValidaXMLResponse();
    }

    /**
     * Create an instance of {@link TestValidaXML }
     * 
     */
    public TestValidaXML createTestValidaXML() {
        return new TestValidaXML();
    }

    /**
     * Create an instance of {@link TestValidaXMLResponse }
     * 
     */
    public TestValidaXMLResponse createTestValidaXMLResponse() {
        return new TestValidaXMLResponse();
    }

    /**
     * Create an instance of {@link ObtenerEstatusCuenta }
     * 
     */
    public ObtenerEstatusCuenta createObtenerEstatusCuenta() {
        return new ObtenerEstatusCuenta();
    }

    /**
     * Create an instance of {@link ObtenerEstatusCuentaResponse }
     * 
     */
    public ObtenerEstatusCuentaResponse createObtenerEstatusCuentaResponse() {
        return new ObtenerEstatusCuentaResponse();
    }

    /**
     * Create an instance of {@link EstatusCuenta }
     * 
     */
    public EstatusCuenta createEstatusCuenta() {
        return new EstatusCuenta();
    }

    /**
     * Create an instance of {@link VerificarStatusSATXML }
     * 
     */
    public VerificarStatusSATXML createVerificarStatusSATXML() {
        return new VerificarStatusSATXML();
    }

    /**
     * Create an instance of {@link VerificarStatusSATXMLResponse }
     * 
     */
    public VerificarStatusSATXMLResponse createVerificarStatusSATXMLResponse() {
        return new VerificarStatusSATXMLResponse();
    }

    /**
     * Create an instance of {@link VerificarStatusSAT }
     * 
     */
    public VerificarStatusSAT createVerificarStatusSAT() {
        return new VerificarStatusSAT();
    }

    /**
     * Create an instance of {@link VerificarStatusSATResponse }
     * 
     */
    public VerificarStatusSATResponse createVerificarStatusSATResponse() {
        return new VerificarStatusSATResponse();
    }

    /**
     * Create an instance of {@link ValidayVerificaXML }
     * 
     */
    public ValidayVerificaXML createValidayVerificaXML() {
        return new ValidayVerificaXML();
    }

    /**
     * Create an instance of {@link ValidayVerificaXMLResponse }
     * 
     */
    public ValidayVerificaXMLResponse createValidayVerificaXMLResponse() {
        return new ValidayVerificaXMLResponse();
    }

    /**
     * Create an instance of {@link TestValidayVerificaXML }
     * 
     */
    public TestValidayVerificaXML createTestValidayVerificaXML() {
        return new TestValidayVerificaXML();
    }

    /**
     * Create an instance of {@link TestValidayVerificaXMLResponse }
     * 
     */
    public TestValidayVerificaXMLResponse createTestValidayVerificaXMLResponse() {
        return new TestValidayVerificaXMLResponse();
    }

    /**
     * Create an instance of {@link Produccion }
     * 
     */
    public Produccion createProduccion() {
        return new Produccion();
    }

    /**
     * Create an instance of {@link Pruebas }
     * 
     */
    public Pruebas createPruebas() {
        return new Pruebas();
    }

}
