
     
INSERT INTO EMPRESA (ID_EMPRESA, RFC, NOMBRE, BIT_ACTIVO, CONTACTO, CORREO, ID_USUARIO_CREADOR) VALUES
     ('1','FERGERGRTHRT','MINISO','1','YASMIN','YAS@MINISO.COM','1');
     
INSERT INTO PROVEEDOR (ID_PROVEEDOR, CLAVE_PROV, RFC, MONEDA, NOMBRE, BIT_ACTIVO, CONTACTO, CORREO, ID_USUARIO_CREADOR) VALUES
     ('1','HOMEDEPT','RTHWERTHER','MXN','HOME DEPOT','1','YASMIN','YAS@HDEPO.COM','1');
     
INSERT INTO FACTURA_NOTA_COMPLEMENTO (UUID, TOTAL, ID_NUM_SAP, SERIE, FOLIO, RFC_EMPRESA, RFC_PROVEEDOR, FECHA_EMISION, FECHA_TIMBRE, NO_CERTIFICADO_EMPRESA, NO_CERTIFICADOSAT, VERSIONCFD, VERSION_TIMBRE, MONEDA, XML_DATE, TIPO_DOCUMENTO, BIT_VALIDOSAT, ESTATUS, RESPUESTA_VALIDACION, BITRS, BITRSUSUARIO ) VALUES
     ('4','3002.32','4','DH35','35','FERGERGRTHRT','RTHWERTHER','6 MARZO','8 ABRIL','4','3','3.3','2','MXN','2 JUNIO','I','1','EN PROCESO','VALIDO','0','0');
     
     INSERT INTO FACTURA_NOTA_COMPLEMENTO (UUID, TOTAL, ID_NUM_SAP, SERIE, FOLIO, RFC_EMPRESA, RFC_PROVEEDOR, FECHA_EMISION, FECHA_TIMBRE, NO_CERTIFICADO_EMPRESA, NO_CERTIFICADOSAT, VERSIONCFD, VERSION_TIMBRE, MONEDA, XML_DATE, TIPO_DOCUMENTO, BIT_VALIDOSAT, ESTATUS, RESPUESTA_VALIDACION, BITRS, BITRSUSUARIO ) VALUES
     ('1','3002.32','1','DH32','32','FERGERGRTHRT','RTHWERTHER','6 MARZO','8 ABRIL','4','3','3.3','2','MXN','2 JUNIO','I','1','PAGADO','VALIDO','1','1');
     
     INSERT INTO FACTURA_NOTA_COMPLEMENTO (UUID,TOTAL, ID_NUM_SAP, SERIE, FOLIO, RFC_EMPRESA, RFC_PROVEEDOR, FECHA_EMISION, FECHA_TIMBRE, NO_CERTIFICADO_EMPRESA, NO_CERTIFICADOSAT, VERSIONCFD, VERSION_TIMBRE, MONEDA, XML_DATE, TIPO_DOCUMENTO, BIT_VALIDOSAT, ESTATUS, RESPUESTA_VALIDACION, BITRS, BITRSUSUARIO ) VALUES
     ('2','3002.32','2','DH33','33','FERGERGRTHRT','RTHWERTHER','6 MARZO','8 ABRIL','4','3','3.3','2','MXN','2 JUNIO','I','1','EN PROCESO','VALIDO','1','1');
     
     INSERT INTO FACTURA_NOTA_COMPLEMENTO (UUID, TOTAL, ID_NUM_SAP, SERIE, FOLIO, RFC_EMPRESA, RFC_PROVEEDOR, FECHA_EMISION, FECHA_TIMBRE, NO_CERTIFICADO_EMPRESA, NO_CERTIFICADOSAT, VERSIONCFD, VERSION_TIMBRE, MONEDA, XML_DATE, TIPO_DOCUMENTO, BIT_VALIDOSAT, ESTATUS, RESPUESTA_VALIDACION, BITRS, BITRSUSUARIO ) VALUES
     ('3','3002.32','3','DH34','34','FERGERGRTHRT','RTHWERTHER','6 MARZO','8 ABRIL','4','3','3.3','2','MXN','2 JUNIO','I','1','CANCELADO','VALIDO','1','1');
     