//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.16 at 07:11:58 PM CDT 
//


package com.canfer.app.wsdl.invoiceone;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pxml" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pusuario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pcontraseña" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pxml",
    "pusuario",
    "pcontrase\u00f1a"
})
@XmlRootElement(name = "ValidayVerificaXML")
public class ValidayVerificaXML {

    protected String pxml;
    protected String pusuario;
    protected String pcontraseña;

    /**
     * Gets the value of the pxml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPxml() {
        return pxml;
    }

    /**
     * Sets the value of the pxml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPxml(String value) {
        this.pxml = value;
    }

    /**
     * Gets the value of the pusuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPusuario() {
        return pusuario;
    }

    /**
     * Sets the value of the pusuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPusuario(String value) {
        this.pusuario = value;
    }

    /**
     * Gets the value of the pcontraseña property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcontraseña() {
        return pcontraseña;
    }

    /**
     * Sets the value of the pcontraseña property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcontraseña(String value) {
        this.pcontraseña = value;
    }

}
